# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
- name: python:3.7
  id: INSTALL
  entrypoint: python3
  args:
  - '-m'
  - 'pip'
  - 'install'
  - '-t'
  - '.'
  - '-r' 
  - 'functions/requirements.txt'
- name: python:3.7
  entrypoint: python3
  id: RUN-LINTER-CHECK
  args:
  - '-m'
  - 'flake8'
  - '--ignore=E501'
  - 'functions/'
  waitFor:
  - INSTALL
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  id: RUN-QUERY_SCRIPT
  args: ['run_query.sh', 'my_query.sql']
  waitFor:
  - RUN-LINTER-CHECK
- name: gcr.io/cloud-builders/gcloud
  args: ['composer', 'environments', 'run', 'ls-dp-imp-v001', '--location', 'europe-west1', 'trigger_dag', '--', 'Trial_DAG']
  id: 'trigger-unit-test-pipeline-execution'  
  waitFor:
  - RUN-QUERY_SCRIPT
- name: python:3.7
  entrypoint: python3
  id: RUN-UNIT-TESTS
  args:
  - '-m'
  - 'nose2'
  - '-s'
  - 'functions'
  - '-c'
  - 'functions/nose2.cfg'
  waitFor:
  - trigger-unit-test-pipeline-execution