MERGE INTO `qintesi-ext-projects.REZ_DETAILED.FCT_CUSTOMER_HISTORY` AS TAR
USING 	(
	select d.ID_CUSTOMER as ID_CUSTOMER, CAST(FORMAT_DATETIME("%Y%m%d", CREATEDDATE) as INT64) as ID_COLLECTION_DATE, 
		   0 as ID_TERRITORY, 0 as ID_GEOGRAPHY, 0 as ID_PLACE, 0 as FA_SALES_RANGE,
		   '' as FA_BLOCKED_REASON_LV, '' as FA_CHURN_REASON_LV, RATING as FA_CUSTOMER_RATING_LV, '' as FA_CUSTOMER_STATUS_LV,
		   '' as FA_IS_SWISS_CANDITATE_FL, TURNOVER_CLASS__C as FA_TURNOVER_CLASS_LV, '' as FA_RENEWAL_MODEL_LV,
		   '' as FA_RENEWAL_PRICING_METHOD_LV, '' as FA_OWNER_STATUS_LV, SUB_STATUS__C as FA_LEAD_SUBSTATUS_LV,
		   '' AS FA_MQ_BRAND_LV, '' as FA_MQ_NEW_LV, '' as FA_MQ_BRANDSHIFT_LV, '' as FA_MQ_LOST_LV,
		   0 as FM_SUM_RISK_AMOUNT, CURRENT_TIMESTAMP() as LOAD_TS
	from `qintesi-ext-projects`.PRZ_SLF.LEAD l 
	INNER JOIN `qintesi-ext-projects`.REZ_DETAILED.DIM_CUSTOMER d on d.TE_SOURCE_CUTOMER_ID = l.ID
	UNION ALL
	select d.ID_CUSTOMER, CAST(FORMAT_DATETIME("%Y%m%d", CREATEDDATE) as INT64) as ID_COLLECTION_DATE, 
		   0 as ID_TERRITORY, 0 as ID_GEOGRAPHY, 0 as ID_PLACE, 0 as FA_SALES_RANGE,
		   a.REASON__C as FA_BLOCKED_REASON_LV, CHURNREASON__C as FA_CHURN_REASON_LV, RATING as FA_CUSTOMER_RATING_LV, STATUS__C as FA_CUSTOMER_STATUS_LV,
		   SWISS_LIST_CANDIDATE__C as FA_IS_SWISS_CANDITATE_FL, TURNOVERCLASS__C as FA_TURNOVER_CLASS_LV, SBQQ__RENEWALMODEL__C as FA_RENEWAL_MODEL_LV,
		   SBQQ__RENEWALPRICINGMETHOD__C as FA_RENEWAL_PRICING_METHOD_LV, APPROVALSTEP__C as FA_OWNER_STATUS_LV, null as FA_LEAD_SUBSTATUS_LV,
		   null AS FA_MQ_BRAND_LV, null as FA_MQ_NEW_LV, null as FA_MQ_BRANDSHIFT_LV, null as FA_MQ_LOST_LV,
		   AMOUNT_AT_RISK__C as FM_SUM_RISK_AMOUNT, CURRENT_TIMESTAMP() as LOAD_TS
	FROM `qintesi-ext-projects`.PRZ_SLF.ACCOUNT a
	INNER JOIN `qintesi-ext-projects`.REZ_DETAILED.DIM_CUSTOMER d on d.TE_SOURCE_CUTOMER_ID = a.ID
	) AS SOU
	ON TAR.ID_CUSTOMER = SOU.ID_CUSTOMER
WHEN NOT MATCHED BY TARGET THEN
	INSERT 
		(ID_CUSTOMER, 
		ID_COLLECTION_DATE, 
		ID_TERRITORY, 
		ID_GEOGRAPHY, 
		ID_PLACE, 
		FA_SALES_RANGE, 
		FA_BLOCKED_REASON_LV, 
		FA_CHURN_REASON_LV, 
		FA_CUSTOMER_RATING_LV, 
		FA_CUSTOMER_STATUS_LV, 
		FA_IS_SWISS_CANDITATE_FL, 
		FA_TURNOVER_CLASS_LV, 
		FA_RENEWAL_MODEL_LV, 
		FA_RENEWAL_PRICING_METHOD_LV, 
		FA_OWNER_STATUS_LV, 
		FA_LEAD_SUBSTATUS_LV, 
		FA_MQ_BRAND_LV, 
		FA_MQ_NEW_LV, 
		FA_MQ_BRANDSHIFT_LV, 
		FA_MQ_LOST_LV, 
		FM_SUM_RISK_AMOUNT, 
		LOAD_TS)
 VALUES (
		ID_CUSTOMER,
		ID_COLLECTION_DATE,
		ID_TERRITORY,
		ID_GEOGRAPHY,
		ID_PLACE,
		FA_SALES_RANGE,
		FA_BLOCKED_REASON_LV,
		FA_CHURN_REASON_LV,
		FA_CUSTOMER_RATING_LV,
		FA_CUSTOMER_STATUS_LV,
		FA_IS_SWISS_CANDITATE_FL,
		FA_TURNOVER_CLASS_LV,
		FA_RENEWAL_MODEL_LV,
		FA_RENEWAL_PRICING_METHOD_LV,
		FA_OWNER_STATUS_LV,
		FA_LEAD_SUBSTATUS_LV,
		FA_MQ_BRAND_LV,
		FA_MQ_NEW_LV,
		FA_MQ_BRANDSHIFT_LV,
		FA_MQ_LOST_LV,
		FM_SUM_RISK_AMOUNT,
		LOAD_TS
	)
WHEN MATCHED THEN
	UPDATE SET
		ID_CUSTOMER=SOU.ID_CUSTOMER,
		ID_COLLECTION_DATE=SOU.ID_COLLECTION_DATE,
		ID_TERRITORY=SOU.ID_TERRITORY,
		ID_GEOGRAPHY=SOU.ID_GEOGRAPHY,
		ID_PLACE=SOU.ID_PLACE,
		FA_SALES_RANGE=SOU.FA_SALES_RANGE,
		FA_BLOCKED_REASON_LV=SOU.FA_BLOCKED_REASON_LV,
		FA_CHURN_REASON_LV=SOU.FA_CHURN_REASON_LV,
		FA_CUSTOMER_RATING_LV=SOU.FA_CUSTOMER_RATING_LV,
		FA_CUSTOMER_STATUS_LV=SOU.FA_CUSTOMER_STATUS_LV,
		FA_IS_SWISS_CANDITATE_FL=SOU.FA_IS_SWISS_CANDITATE_FL,
		FA_TURNOVER_CLASS_LV=SOU.FA_TURNOVER_CLASS_LV,
		FA_RENEWAL_MODEL_LV=SOU.FA_RENEWAL_MODEL_LV,
		FA_RENEWAL_PRICING_METHOD_LV=SOU.FA_RENEWAL_PRICING_METHOD_LV,
		FA_OWNER_STATUS_LV=SOU.FA_OWNER_STATUS_LV,
		FA_LEAD_SUBSTATUS_LV=SOU.FA_LEAD_SUBSTATUS_LV,
		FA_MQ_BRAND_LV=SOU.FA_MQ_BRAND_LV,
		FA_MQ_NEW_LV=SOU.FA_MQ_NEW_LV,
		FA_MQ_BRANDSHIFT_LV=SOU.FA_MQ_BRANDSHIFT_LV,
		FA_MQ_LOST_LV=SOU.FA_MQ_LOST_LV,
		FM_SUM_RISK_AMOUNT=SOU.FM_SUM_RISK_AMOUNT,
		LOAD_TS=SOU.LOAD_TS	